name: actionlint

on:
  pull_request:
    paths:
      - ".github/actions/**"
      - ".github/workflows/**"

permissions:
  contents: read
  pull-requests: write

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: reviewdog/action-actionlint@ab7138020abfe6cd20b742c82e5b7a9749fb5884 # v1.75.0
        with:
          reporter: github-pr-review
          fail_level: error
