name: Check spelling
permissions:
  contents: read
on:
  pull_request: null
jobs:
  spellcheck:
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: streetsidesoftware/cspell-action@de2a73e963e7443969755b648a1008f77033c5b2 # v8.4.0
        with:
          incremental_files_only: true
          strict: false
