# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will install Deno then run `deno lint` and `deno test`.
# For more information see: https://github.com/denoland/setup-deno

name: Deno

on:
  push:
    branches:
      - "main"
  pull_request:
    paths:
      - "**.json"
      - "**.ts"
      - "**.tsx"
      - "**.md"

permissions:
  contents: read

jobs:
  test:
    timeout-minutes: 5
    runs-on: ubuntu-22.04

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v1.x

      - run: deno fmt --check
      - run: deno lint
      - run: deno test -A --coverage=coverage
      - run: deno coverage ./coverage --lcov > coverage.lcov

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: ./coverage.lcov
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
