# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will install Deno then run `deno lint` and `deno test`.
# For more information see: https://github.com/denoland/setup-deno

name: Deno

on:
  push:
    branches:
      - "main"
    paths:
      - "**.json"
      - "**.ts"
      - "**.tsx"
  pull_request:
    paths:
      - "**.json"
      - "**.ts"
      - "**.tsx"

permissions:
  contents: read

jobs:
  test:
    timeout-minutes: 5
    runs-on: ubuntu-latest

    strategy:
      matrix:
        year: [2023, 2022]

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Verify formatting
        run: deno fmt --check

      - name: Run linter
        run: deno lint

      - run: deno cache __tests__/deps.ts
      - run: find posts/${{ matrix.year }} -name '*.md' | sort | xargs -I file deno task lint -c .textlintrc.json file

      - name: Run tests
        run: deno test -A --coverage=coverage

      - name: Create coverage report
        run: deno coverage ./coverage --lcov > coverage.lcov

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.lcov
          fail_ci_if_error: true
