name: Deploy
on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-22.04

    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v5

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v1.x

      - name: Update Algolia Index
        if: github.ref == 'refs/heads/main'
        run: deno run -A scripts/update_algolia_index.ts
        env:
          ALGOLIA_APP_ID: ${{ secrets.ALGOLIA_APP_ID }}
          ALGOLIA_ADMIN_KEY: ${{ secrets.ALGOLIA_ADMIN_KEY }}
          ALGOLIA_INDEX_NAME: ${{ secrets.ALGOLIA_INDEX_NAME }}

      - name: Build step
        run: "deno task build"

      - name: Upload to Deno Deploy
        if: github.ref == 'refs/heads/main'
        uses: denoland/deployctl@v1
        with:
          project: "9renpoto"
          entrypoint: "main.ts"
          root: "."
