name: Feed to social media
on:
  workflow_dispatch:
  schedule:
    - cron: "15 3,10 * * *"

permissions:
  contents: write # To write the generated contents to the readme

jobs:
  Feed2SocialMedia:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Feed to social media
        uses: lwojcik/github-action-feed-to-social-media@v2.4.1
        with:
          feedUrl: "https://9renpoto.win/rss.xml"
          newestItemStrategy: "latestDate"
          postFormat: "Blogged: {title}\n\n{link}"
          # Twitter settings
          twitterEnable: true
          twitterPostFormat: "Blogged: {title}\n\n{link}?utm_source=twitter"
          twitterApiKey: ${{ secrets.X_API_KEY }}
          twitterApiKeySecret: ${{ secrets.X_API_SECRET }}
          twitterAccessToken: ${{ secrets.X_ACCESS_TOKEN }}
          twitterAccessTokenSecret: ${{ secrets.X_ACCESS_TOKEN_SECRET }}
          # Bluesky settings
          blueskyEnable: true
          blueskyPostFormat: "Blogged: {title}\n\n{link}?utm_source=bsky"
          blueskyAppPassword: ${{ secrets.BSKY_APP_PASSWORD }}
          blueskyHandle: "9renpoto.win"
          blueskyOwnerHandle: "9renpoto.win"
          blueskyOwnerContact: "9renpoto+bsky@gmail.com"
