name: Node

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: write
  pull-requests: write
  actions: write

jobs:
  test:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Setup Homebrew
        uses: Homebrew/actions/setup-homebrew@fccef3b26268fc4a788fd7ad7c189f3a105cbf13
      - name: Install developer tools
        run: brew bundle install --file=Brewfile
      - name: Setup Node
        uses: actions/setup-node@949feb2413d6458794dcd2491c4babbbce0c15c1 # v7.1.0
        with:
          node-version: "24" # Node.js 24 LTS
          cache: npm
      - run: npm ci
      - run: npm run content:generate
      - name: Run prek hooks
        run: prek run --all-files
      - run: npm run test:coverage
      - run: npm run build
      - run: npx playwright install --with-deps chromium
      - run: npm run test:browser
      - name: Run octocov
        uses: k1LoW/octocov-action@v1
