name: textlint

on:
  push:
    branches: [main]
    paths:
      - "posts/**/*.md"
      - ".textlintrc.json"
      - "package.json"
      - "package-lock.json"
      - ".node-version"
      - ".github/workflows/textlint.yml"
  pull_request:
    paths:
      - "posts/**/*.md"
      - ".textlintrc.json"
      - "package.json"
      - "package-lock.json"
      - ".node-version"
      - ".github/workflows/textlint.yml"

permissions:
  contents: read

jobs:
  lint:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    strategy:
      matrix:
        year: [2026, 2025, 2024, 2023, 2021]
    steps:
      - name: Setup repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Setup Node
        uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6
        with:
          node-version-file: .node-version
          cache: npm
      - run: npm ci
      - name: Run textlint
        run: npm run textlint -- "posts/${{ matrix.year }}/**/*.md"
